// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmzptynzlwuxxuthpoov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtenB0eW56bHd1eHh1dGhwb292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjM0MjMsImV4cCI6MjA2NzYzOTQyM30.7ef0uWx2KId99OasTo85fVcaWe7s4riA9kFVr-s3mxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});